apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-credentials
  namespace: myapp
spec:
  encryptedData:
    token: AgA9mso/vCyc40lZ3Lm3RK7L1fVR1KqQqqewyPeyMK9Pt0+RxxxK5MEePtlHXkALU+GFvN2gozQfOEdttMM+1ykuHl7Gf5WoiNe0EDuOr0+Tgku/JW9II66QbDfscDGsLaICDNeP42Ii0C4c2q1FCkcIj0L/rvIOHEDYgJS+TK8DIzzlyvXUP2KB6aP5GkSLGEZMYg5BzwgMGnAjajiu9xaI/w+Pqns0xah0anIlHyq1QnIR3tiduw3h7rUzlptolvrFeTAuVM4X4cTGXjA/ys3iH2Pz+0ZhFVbXkPnuscwqwkwqaFt9SHqOwrlB9RNbuXVHOVRNs3spLVBBv/XuwPwOYQt86/FAVilD1soOCWwdRBsOCShHeiJ3JLeoMRhewZL2YxvwJ+uBt5Cydvi+aPpEyJMHhrbsL5HHb6UQRYxe6udAmEFqqY7D213+NlE0AAjILDq9JvYMygsJ0NInPYe+0vf9OpIqzkzqOZb6qcJH+zVHhajTKCp6eEGBqePaF+ifhMr0mHTES9w/Vth+DN0C2sX6dWZPbK8w7DXHvw6N5ePZ0ic+m4Kc79oPMh9Oi/YZubCVLEJix7Oi9JSWD9Ov744xCzaK6TOO9UTBKniI0VYkRyYtoEW6w5+SzN3lAwzbkYRbevl27pYJIiwwag23YC2Fw1g/iZW1E4aI5eFaVSFSBdLF6zANZIuIBMRPiK51XSkPlK7FdkJqI/dygNe2Vty6Fw==
    webhook-secret: AgBqVfhXjXPV8YI54hesLXsLS2ZqlcQ3VcbfF1nPSTPpd7oYE+pijS9A8Y4lOK0hD/apETKHFWWvolY6b2EhckI7wwhPJlkdtgyZDAd8LRy49PqxmjAKGFAk1gmrSQYPmSEXbSf0NIlI0F7KY/qCMTECY2RnrTcweZdUjDitPAQvHunPytdfl3VK4ojU3+9xBWU4ymlbC1zUAZbuGb+toxwpMknCE4mGdrkCVcG4s6hT7zhyHMwEKk44iyBm8HdK7ZLzVBiHwuHu7EQ13w95e/KXgpmQIDMbuo+IQvA32RZ0UXEbv1KczxVC01URF8XSU9KkfbLAmrBiA6vHr1GjdqmCF9IXCGdLG4HTJxKHsHKcQ4hjX+vLNqQ/x8DwvN/Q5PdduljkV9XNsb09le9B9d7DBAF8xrEsmR14vg9Y6GYGRHuc3kPdS9BeR94f2ze/WuMrS9QC3nSxvyMsOLPJhR4rtmgXqTbZBCCSo8nBUgTs1wi+9rg1e9G0Pe5DMLGA8m05bxQxP4Ow4OO2lwgf7rigtHxeAI30lvkHEe50TjvfYKP6JPPKCUPMiFrymmObB5oVN9Ec0L9cEv+yo5F5Ry81lBSgOONX6M+AJw7aBffrJaoGEzdbIZnaT7fKtk6nikk1Bkj5/AIeYtF9IiWnIfC+8MFOY+UH3egowcGSambDsWN9CTqIV8J25xpyBbQzL1qlc94UKy2bA1ww
  template:
    metadata:
      creationTimestamp: null
      name: api-credentials
      namespace: myapp
---
