apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-password
  namespace: myapp
spec:
  encryptedData:
    password: AgBTPy1W5MbepWYz+HgiR7cILlYPu38kSzd+w/mUn0z1N193rRFzqcxAFrGLtOJbF1G0PsKCOAMOkY0vOf9x3ivOkb4QBiDbfCxa+Wq7A8c+xXHP6rFSU02SzJgm/pH78siRRttWTTeZSMH2FvSOIL262Zckjahio3I1XjEyBi+QSeJZNrvO01BjiXBv0ig/XX1Wo/J/T7RrtpRr8exjQXW5qWNwFV2ww4lbUpbRyaB5iA4BqpGaT9czlYjqvVNsfsyIKOVnCOnH0LjgvY/5dt35Yz+i79Ye+TdA10IxdMnwDXA0OgMM7HULNOVAZYuAuUN0BMMY0gV99ziMztJVwmiBFjgiquKd+uyutGfxnsO2yNuwGR9wcjRhco0Yrtu7Q03iHZuqwzu/2ZnQ0+2XDUuFPHlgtd1OCrNyB1dw+2ggi3URMDxFzr+HmEmL6znF9GrgItbsIZNFQzDydu+ZBw+ZtP1rsp6nTG/dN2czpuXWKE/O4sfGBcukZDP1XiAFTuaJvgYFlcAR2ov1JggEccpSTQ6zpV74PcH6fStMT9qjN33ai2N0e5FuevriUqNvJsY1Q141Vxg+0LugKl4J+bC0ZkSzS4EvVD/V8ibE82Y0De08sGgK7+DdmjqPcOoWvgY8BaFxJsC4YXLA3+BXIEP9YniAAGcfQ0q7uGB51UBTOc9gjTltyVukf8O/SbBYUazLXGN0+Squ6Tgr/GZ55A==
  template:
    metadata:
      creationTimestamp: null
      name: db-password
      namespace: myapp
---
